projects:
  server:
    schemaPath: src/generated/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
      prepare-binding:
        generator: binding-ts
        output: src/generated/kudos.ts
