projects:
  server:
    schemaPath: src/generated/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
      codegen:
        - generator: graphql-binding
          language: typescript
          output:
            binding: src/generated/prisma.ts
